# .github/actions/aws-cli-action/action.yml
name: 'AWS CLI Action'
description: 'A custom action to run AWS CLI commands'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  aws-cli-command:
    description: 'AWS CLI command to run'
    required: true
runs:
  using: 'composite'
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_REGION: ${{ inputs.aws-region }}
  steps:
    - name: Set up AWS CLI
      run: |
        echo "Configuring AWS CLI..."
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION
      shell: bash

    - name: Run AWS CLI command
      run: |
        echo "Running AWS CLI command..."
        aws ${{ inputs.aws-cli-command }}
      shell: bash
