# .github/actions/aws-cli-action/action.yml
name: 'AWS CLI Action'
description: 'A custom action to run AWS CLI commands'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  aws-cli-command:
    description: 'AWS CLI command to run'
    required: true
outputs:
  command-output:
    description: 'The output from the AWS CLI command'
runs:
  using: 'composite'
  steps:
    - name: Set up AWS CLI
      run: |
        echo "Configuring AWS CLI..."
        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
        aws configure set default.region ${{ inputs.aws-region }}
      shell: bash

    - name: Run AWS CLI command
      id: run_aws_command
      run: |
        echo "Running AWS CLI command..."
        output=$(aws ${{ inputs.aws-cli-command }})
        echo "command-output=$output" >> $GITHUB_OUTPUT
      shell: bash
