# .github/actions/get_resource_by_id/action.yml
name: 'Retrieve id of resource by name or tag key-value pair'
description: 'This action retrieves the id/dns name etc of the resource'
inputs:
  aws-access-key-id:
      description: 'AWS Access Key ID'
      required: true
  aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
  aws-region:
      description: 'AWS Region'
      required: true
  resource-type:
        description: 'The type of resource for whome id is required.Possible values are: ALB'
        required: false
        default: 'ALB'
  resource-name:
        description: 'Resource name for which id is needed'
        required: true
        default: ''
  resource-tag-name:
        description: 'Resource tag name'
        required: false
        default: ''
  resource-tag-value:
        description: 'Resource tag value'
        required: false
        default: ''
outputs:
  resource-id:
    description: 'Resource id'
    value: ${{ steps.retrieve-hosted-zone-id.outputs.resource-id }}
runs:
  using: 'composite'
  steps:
    - name: Retrieve hosted-zone id
      if: ${{ inputs.resource-type == 'hosted-zone' }}
      id: retrieve-hosted-zone-id
      run:  |  
        tagKey=${{ inputs.resource-tag-name }}
        tagValue=${{ inputs.resource-tag-value }}
        resourceName=${{ inputs.resource-name }}

        if [ -z "${{ inputs.resource-name }}" ]; then
            # Retrieve by tag
            hosted_zone_ids=$(aws route53 list-hosted-zones --query 'HostedZones[*].Id' --output text)
         

            # Step 2: Find the hosted zone by its tag
            for temp_id in $hosted_zone_ids; do
                 id=$(echo $temp_id | sed 's#/hostedzone/##')
                 tag= $(aws route53 list-tags-for-resource --resource-type hostedzone --resource-id $id  --query ResourceTagSet.Tags[?Key==\`${tagKey}\`] --output text)

                 echo "Output tag value-$tag"
                               
                if [[ "$tag" == *${tagValue}*  ]]; then
                  hostedzone_id=$id
                  break;
                fi 
            done
        else
             hostedzone_id=$(aws route53 list-hosted-zones --query HostedZones[?Name==/`${resourceName}/`].Id --output text)
             echo "HostedZone-$hostedzone_id"
            
        fi;
        echo "Resource-id:$hostedzone_id"
        echo "resource-id=$hostedzone_id">> "$GITHUB_OUTPUT" 
      shell: bash
