name: Run AWS FIS Experiment

on:
  workflow_call:
    inputs:   
      AWS_ACCESS_KEY_ID:
            required: true
            type: string
      AWS_SECRET_ACCESS_KEY:
            required: true
            type: string
      
jobs:
  run-fis-experiment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables from File
      uses: ./.github/actions/setup-environment
      with:
          var_file_path: ./.github/variables/fis_aws.env      

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Start FIS experiment
      id: start_experiment
      run: |
        experiment_id=$(aws fis start-experiment --region $AWS_REGION --experiment-template-id ${{ github.event.inputs.EXPERIMENT_TEMPLATE_ID }} --query 'experiment.id' --output text)
        echo "experiment_id=${experiment_id}" >> $GITHUB_ENV
        echo "Experiment started with ID: $experiment_id"

    - name: Monitor FIS experiment
      run: |
        state="running"

        while [[ "$state" == *running* ||   "$state" == *initiating* ]]; do        
          state=$(aws fis get-experiment --region $AWS_REGION --id ${{ env.experiment_id }} --query 'experiment.state' --output text)
          echo "Current state: $state"
          sleep 120
        done
        echo "Experiment completed with state: $state"
