name: CI

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            from:  meenalgoyal02@gmail.com
            to: meenalgoyal02@gmail.com
            username:  meenalgoyal02@gmail.com
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: Test Email
            body: This is a test email sent from GitHub Actions.
            html_body: |
                <h1>This is a test email</h1>
                <p>Test Paragraph</p>
           
        
