name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run some build step
        run: |
          # Simulate a build step
          echo "Running build step..."
          # Simulate a failure
          exit 1

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 587
            username: meenalgoyal02@gmail.com
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: GitHub Actions Job Failed
            body: The GitHub Actions job failed. Please check the logs for more details.
            to: meenal.goyal@nagarro.com
            from: meenalgoyal02@gmail.com
            secure: true
        
