name: CI

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            from:  meenalgoyal02@gmail.com
            to: meenalgoyal02@gmail.com
            username:  meenalgoyal02@gmail.com
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: Test Email
            body:  |
                The GitHub Actions job failed. Please check the logs for more details.
                Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}            
           
        
