name: CI

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: hilarion5/send-mail@v1
        with:
            smtp-server: smtp.example.com
            smtp-port: 465
            smtp-secure: true
            from-email:  meenalgoyal02@gmail.com
            to-email: meenalgoyal02@gmail.com
            username:  meenalgoyal02@gmail.com
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: Test Email
            body: This is a test email sent from GitHub Actions.
            html: |
                <h1>This is a test email</h1>
                <p>Test Paragraph</p>
           
        
