name: Simulate disaster in specified region.
on:  
  workflow_call:
      inputs:
        resource_type:
          description: 'The type of resource to bring down'
          default: 'ec2'
          required: true
          type: string
      secrets:    
        AWS_ACCESS_KEY_ID:
              required: true              
        AWS_SECRET_ACCESS_KEY:
                  required: true
        SMTP_PASSWORD:
                required: true
      outputs:
            region-failover-successful:
              description: "Boolean value to indicate whether region down was successful or not"
              value: ${{ jobs.aws-cli-in-github-actions.outputs.region-down-or-not }}   
            conclusion:
               description: "Conclusion text that can be sent for notification"             
               value: ${{ jobs.aws-cli-in-github-actions.outputs.conclusion }}   


jobs:
    aws-cli-in-github-actions:
      outputs: 
        region-down-or-not: ${{ steps.verify-region-is-down.outputs.Region-down }}
        conclusion: ${{ steps.conclusion.outputs.value }}
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set Environment Variables from File
          if: ${{ inputs.resource_type == 'ec2'}}
          uses: ./.github/actions/setup-environment
          with:
              var_file_path: ./.github/variables/disaster_aws.env
        
        - name: Set Environment Variables from File
          if: ${{ inputs.resource_type == 'ecs'}}
          uses: ./.github/actions/setup-environment
          with:
              var_file_path: ./.github/variables/disaster_ecs.env

        - uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install awscli 
        
        - name: start date and time
          id: start-date
          run: |
             currentDate=$(echo $(date))
             echo "Current date-${currentDate}"
             echo "value=$currentDate">>"$GITHUB_OUTPUT"
            
        - name: Retrieve DNS name of load balancer
          continue-on-error: true
          id: primary-alb-dns-name 
          uses: ./.github/actions/get_resource_by_id
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}            
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}              
            aws-region: ${{ env.AWS_REGION }}              
            resource-type: 'ALB'               
            resource-name: ''  # Get from environment             
            resource-tag-name: ${{ env.TAG_KEY }}              
            resource-tag-value: ${{ env.TAG_VALUE }}   
                    
        - name: Retrieve id of hosted-zone 
          continue-on-error: true
          id: get-hosted-zone-id-by-name
          uses: ./.github/actions/get_resource_by_id
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}            
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}              
            aws-region: ${{ env.AWS_REGION }}              
            resource-type: 'hosted-zone'               
            resource-name: ${{ env.HOSTED-ZONE-NAME }}               
            resource-tag-name: ''              
            resource-tag-value: ''

        - name: Set primary region CNAME weight to 0
          continue-on-error: true
          id: disaster-in-primary-region
          if: ${{ steps.primary-alb-dns-name.outputs.resource-id !='' }}
          run: |
               hosted_zone_id=${{ steps.get-hosted-zone-id-by-name.outputs.resource-id }}
               alb_id=${{ steps.primary-alb-dns-name.outputs.resource-id }}
               echo "Hosted-zone id-$hosted_zone_id, ALB id-$alb_id"
               #echo "DNS name of ALB-${{ steps.primary-alb-dns-name.outputs.resource-id }}"
               
               CHANGE_OUTPUT=$(aws route53 change-resource-record-sets --hosted-zone-id ${hosted_zone_id} --change-batch "{ \"Comment\": \"Changes weights of ACTIVE region from 100 to 0\",\"Changes\": [{ \"Action\": \"UPSERT\",
               \"ResourceRecordSet\": {\"Name\": \"${{ env.CNAME }}\", \"Type\": \"CNAME\", \"SetIdentifier\": \"${{ env.PRIMARY_CNAME_IDENTIFIER }}\",\"Weight\": 0,\"TTL\":60,\"ResourceRecords\":[{\"Value\":\" ${alb_id} \"}]  }}]}")
               
                echo "Change Output: $CHANGE_OUTPUT"
                CHANGE_ID=$(echo $CHANGE_OUTPUT | jq -r '.ChangeInfo.Id')
                echo "Change ID: $CHANGE_ID"
                echo "::set-output name=change_id::$CHANGE_ID"

        - name: Wait for Route53 Change to Become INSYNC
          if: ${{ steps.disaster-in-primary-region.outcome == 'success' }}
          id: wait-for-insync-primary
          run: |
                   CHANGE_ID=${{ steps.disaster-in-primary-region.outputs.change_id }}
                   STATUS="PENDING"
                   while [ "$STATUS" != "INSYNC" ]; do
                     echo "Waiting for change $CHANGE_ID to become INSYNC..."
                     STATUS=$(aws route53 get-change --id $CHANGE_ID | jq -r '.ChangeInfo.Status')
                     echo "Current status: $STATUS"
                     if [ "$STATUS" != "INSYNC" ]; then
                       echo "Not in sync yet. Sleeping for 30 seconds..."
                       sleep 30
                     fi
                   done
                   echo "Change $CHANGE_ID is now INSYNC." 

        - name: Retrieve ecs cluster arn
          continue-on-error: true
          id: get-ecs-cluster-by-tag-name
          if: ${{ steps.disaster-in-primary-region.outcome == 'success' &&  inputs.resource_type == 'ecs' }}
          uses: ./.github/actions/get_resource_by_id
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}            
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}              
            aws-region: ${{ env.AWS_REGION }}              
            resource-type: 'ecs-cluster'               
            resource-name: ''              
            resource-tag-name: ${{ env.TAG_KEY }}              
            resource-tag-value: ${{ env.TAG_VALUE }}

        - name: Retrieve ecs service arn
          continue-on-error: true
          id: get-ecs-service-id
          if: ${{ steps.get-ecs-cluster-by-tag-name.outputs.resource-id !='' &&  inputs.resource_type == 'ecs' }}
          uses: ./.github/actions/get_resource_by_id
          with:
            aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}            
            aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}              
            aws-region: ${{ env.AWS_REGION }}              
            resource-type: 'ecs-service'               
            resource-name: ${{ steps.get-ecs-cluster-by-tag-name.outputs.resource-id }}              
            resource-tag-name: ${{ env.TAG_KEY }}              
            resource-tag-value: ${{ env.TAG_VALUE }}


        - name: Set instance capacity in primary region
          id: disaster-simulation-ASG  
          if: ${{ steps.disaster-in-primary-region.outcome == 'success' }}
          continue-on-error: true     
          run: |
            input_resource=${{ inputs.resource_type }}
            if [[ "$input_resource" == "ec2" ]]; then
               aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --desired-capacity $DESIRED_CAPACITY --min-size $MIN_CAPACITY --max-size $MAX_CAPACITY --region $AWS_REGION
            else
                clusterId=${{ steps.get-ecs-cluster-by-tag-name.outputs.resource-id }}
                serviceId=${{ steps.get-ecs-service-id.outputs.resource-id }}
                echo "ECS service id-$serviceId"
                aws ecs update-service --cluster $clusterId --service $serviceId --desired-count $DESIRED_CAPACITY --region $AWS_REGION
            fi
        - name: Verify whether the URL is down or not
          continue-on-error: true
          if: ${{ steps.disaster-in-primary-region.outcome == 'success' }}
          id: verify-region-is-down
          run: |  
            sleep 120                   
            HTTP_STATUS=$(curl -s -o /dev/null -I -w "%{http_code}" "${{ env.CNAME }}")
            echo "HTTP Status- ${HTTP_STATUS}"
            if [ "$HTTP_STATUS" -eq 503 ]; then
              echo "Region down completed."
              echo "::set-output name=Region-down::true"
              echo "::set-output name=Email-subject:: AWS region is down for Repository- ${{ github.repository }}"
            else
              echo "Region down could not be completed."
              echo "::set-output name=Region-down::false"
              echo "::set-output name=Email-subject:: Failed in setting AWS region down. "
            fi
        
        - name: end date and time
          id: end-date
          run: |
              currentDate=$(echo $(date))
              echo "Current date-${currentDate}"
              echo "value=$currentDate">>"$GITHUB_OUTPUT"
        - name: action run summary
          continue-on-error: true
          id: conclusion
          run: |

            outcomeOfHostUpdate="${{ steps.disaster-in-primary-region.outcome }}"
            outcomeOfASGUpdate="${{ steps.disaster-simulation-ASG.outcome }}"

            if [[ "$outcomeOfHostUpdate" == "success" || "$outcomeOfASGUpdate" == "success" ]]; then
              value="<h3>Region failure simulation completed successfully.</h3>"
            else
              value="<h3>Region failure simulation failed.</h3>"
            fi;

            input_resource=${{ inputs.resource_type }}
            if [[ "$input_resource" == "ec2" ]]; then
              impactedResources="<ol> <li>ASG: ${{ env.ASG_NAME }}</li> <li>Hosted-zone:${{ env.CNAME }}</li> </ol>"
            else
              impactedResources="<ol> <li>ECS Service: ${{ steps.get-ecs-service-id.outputs.resource-id }}</li> <li>Hosted-zone:${{ env.CNAME }}</li> </ol>"
            fi;
           
            value+="<h4>Conclusion :${{ steps.verify-region-is-down.outputs.Email-subject }}</h4><figure class="table"> <table> <tbody> <tr> <td>1.</td> <td><strong>Activity Name</strong></td> <td>AWS Region failure simulation</td> <td>&nbsp;</td> </tr> <tr> <td>2.</td> <td><strong>AWS Region</strong></td> <td>${{ env.AWS_REGION }}</td> <td>&nbsp;</td> </tr> <tr> <td>3.</td> <td><strong>Impacted resources</strong></td> <td> ${impactedResources} </td> <td>&nbsp;</td> </tr> <tr> <td>4.</td> <td><strong>Activity Start Time</strong></td> <td>${{ steps.start-date.outputs.value }}</td> <td>&nbsp;</td> </tr> <tr> <td>5.</td> <td><strong>Activity End Time</strong></td> <td>${{ steps.end-date.outputs.value }}</td> <td>&nbsp;</td> </tr></tr> <tr> <td>6.</td> <td><strong>Service Name </strong></td>  <td>&nbsp;</td> </tr><tr> <td>7.</td> <td><strong>CI Id </strong></td>  <td>&nbsp;</td></tr> </tbody> </table> </figure>"
            
            echo "value=$value">>"$GITHUB_OUTPUT"
            echo "Email content-$value"

      