name: Simulation of outage in the Primary AWS region
on: 
  workflow_dispatch:
     inputs:
        outage-type:
          description: 'Select the failover type to run'
          required: true
          default: 'disaster'
          type: choice
          options:
            - region-failover
            - system-failover

jobs:
  call-workflow-passing-data:
    if: ${{github.event.inputs.outage-type=='region-failover'}}
    uses: ./.github/workflows/disaster_aws.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}     
  run-experiment:
    if: ${{github.event.inputs.outage-type=='system-failover'}}
    uses: ./.github/workflows/aws_fault_experiment.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}        
       