name: Simulation of outage in the Primary AWS region
on: 
  workflow_dispatch:
     inputs:
        outage-type:
          description: 'Select the failover type to run'
          required: true
          default: 'disaster'
          type: choice
          options:
            - region-failover
            - system-failover

jobs:
  run-region-failover:
    if: ${{github.event.inputs.outage-type=='region-failover'}}
    uses: ./.github/workflows/disaster_aws.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  

  run-recovery-scripts:
     needs: run-region-failover
     uses: ./.github/workflows/recovery_aws.yml
     secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}          
 
  run-experiment:
    if: ${{github.event.inputs.outage-type=='system-failover'}}
    uses: ./.github/workflows/aws_fault_experiment.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   

  send-disaster-simulation-notification:
    needs: 
      - run-region-failover
      - run-recovery-scripts
    runs-on: ubuntu-latest
    steps:
      - name: send notification email
        id: notification-email
        if: ${{github.event.inputs.outage-type=='region-failover'}}
        run: |
          content="<html><body><h1>Gameday Preparation completed with the run of GitHub workflow </h1>"
          content+="${{ needs.run-region-failover.outputs.conclusion }}"
          content+="<br/>"
          content+="${{ needs.run-recovery-scripts.outputs.conclusion }}"

          content+="<br><p>Click <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">here </a>to view the workflow logs.&nbsp;</p></body><html>"
       