name: Workflow for simulation of outage in the Primary AWS region
on: 
  workflow_dispatch

env:  
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  call-disaster-simulator:
       uses: ./.github/workflows/disaster_aws.yml
       secrets:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  # run-experiment:
  #       uses: 