name: Simulation of outage in the Primary AWS region
on: 
  workflow_dispatch:
     inputs:
        outage-type:
          description: 'Select the failover type to run'
          required: true
          default: 'disaster'
          type: choice
          options:
            - region-failover
            - system-failover
env:
  SENDER_EMAIL_ID: 'meenalgoyal02@gmail.com'
  RECEIVER_EMAIL_ID: 'meenal.goyal@nagarro.com'

jobs:
  run-region-failover:
    if: ${{github.event.inputs.outage-type=='region-failover'}}
    uses: ./.github/workflows/disaster_aws.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  

  run-recovery-scripts:
     needs: run-region-failover
     uses: ./.github/workflows/recovery_aws.yml
     secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}          
 
  run-experiment:
    if: ${{github.event.inputs.outage-type=='system-failover'}}
    uses: ./.github/workflows/aws_fault_experiment.yml
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   

  send-disaster-simulation-notification:
    needs: [run-region-failover, run-recovery-scripts, run-experiment]

    runs-on: ubuntu-latest
    steps:
      - name: send notification email
        continue-on-error: true
        id: notification-email-content
        if: ${{github.event.inputs.outage-type=='region-failover'}}
        run: |
          content="<html><body>"
          if [[ "${{ github.event.inputs.outage-type }}" == "region-failover" ]]; then             
            content+="${{ needs.run-region-failover.outputs.conclusion }}"
            content+="<br/>"
            content+="${{ needs.run-recovery-scripts.outputs.conclusion }}"
          else 
            content+="${{ needs.run-experiment.outputs.conclusion }}"
          fi;
          content+="<br><p>Click <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">here </a>to view the workflow logs.&nbsp;</p></body><html>"
          echo "Email content:${content}"
          echo "content=$content">>"$GITHUB_OUTPUT"

      - name: Send notification email   
        continue-on-error: true       
        uses: dawidd6/action-send-mail@v3
        with:
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              from:  ${{ env.SENDER_EMAIL_ID }}
              to: ${{ env.RECEIVER_EMAIL_ID }}
              username:  ${{env.SENDER_EMAIL_ID}}
              password: ${{ secrets.SMTP_PASSWORD }}
              subject: 'Region failover completed'                 
              html_body: |
                ${{ steps.notification-email-content.outputs.content}}
       