name: DB script using matrix 

on: push

env:
  AWS_REGION: 'us-east-1'
  RDS_HOST: 'pocdb1.ciwtq0frolty.us-east-1.rds.amazonaws.com'
  RDS_PORT: '5432'
  RDS_USERNAME: 'postgres'
  PGPASSWORD: ${{ secrets.RDS_PASSWORDS }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  migration-required-or-not:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: 'src/migrations/ddl'
            migration_column: 'ddl' 
          - folder: 'src/migrations/triggers'
            migration_column: 'triggers' 
          - folder: 'src/migrations/stored_procedures'
            migration_column: 'stored_procedure'             
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Get migration history version
        id: get_migration_history
        run: |          
          query_output=$(psql -h $RDS_HOST -p $RDS_PORT -U $RDS_USERNAME -d poc -t -c "select ${{ matrix.migration_column }} from \"_MigrationsHistory\" order by migration_id desc limit 1" 2>&1)
          echo "Output- $query_output"

          echo "${{ matrix.migration_column }}=$query_output" >> $GITHUB_OUTPUT
        #   echo "::set-output name=migration_history_version::$query_output"
        #   echo "MigrationHistoryVersion=$query_output" >> "$GITHUB_OUTPUT"
    outputs:
            ddl: ${{ steps.get_migration_history.outputs.ddl }}
            triggers: ${{ steps.get_migration_history.outputs.triggers }}
            stored_procedure: ${{ steps.get_migration_history.outputs.stored_procedure }}
  get-files-from-folder:
    runs-on: ubuntu-latest
    needs: migration-required-or-not          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Print results of above step
        run: |
         echo 'Result of ddl- ${{ needs.migration-required-or-not.outputs.ddl }}'
         echo 'Result of ddl- ${{ needs.migration-required-or-not.outputs.triggers }}'
         echo 'Result of ddl- ${{ needs.migration-required-or-not.outputs.stored_procedure }}'

